syntax on
set nu rnu
call plug#begin() 
    source $HOME/code/repos/dotfiles/vim/plugins/plugins.vim 
call plug#end()
source $HOME/code/repos/dotfiles/vim/default_settings.vim
source $HOME/code/repos/dotfiles/vim/plugins/coc.vim
source $HOME/code/repos/dotfiles/vim/plugins/copilot.vim
source $HOME/code/repos/dotfiles/vim/plugins/fzf.vim
source $HOME/code/repos/dotfiles/vim/plugins/gitgutter.vim
source $HOME/code/repos/dotfiles/vim/plugins/indentguides.vim
source $HOME/code/repos/dotfiles/vim/plugins/magit.vim
source $HOME/code/repos/dotfiles/vim/plugins/mappings.vim
source $HOME/code/repos/dotfiles/vim/plugins/tree.vim
source $HOME/code/repos/dotfiles/vim/plugins/window-swap.vim
source $HOME/code/repos/dotfiles/vim/default_settings.vim
