syntax on
set nu rnu
call plug#begin() 
    source /home/anirudh/code/repos/dotfiles/vim/plugins/plugins.vim 
call plug#end()
source /home/anirudh/code/repos/dotfiles/vim/default_settings.vim
source /home/anirudh/code/repos/dotfiles/vim/plugins/coc.vim
source /home/anirudh/code/repos/dotfiles/vim/plugins/copilot.vim
source /home/anirudh/code/repos/dotfiles/vim/plugins/fzf.vim
source /home/anirudh/code/repos/dotfiles/vim/plugins/gitgutter.vim
source /home/anirudh/code/repos/dotfiles/vim/plugins/indentguides.vim
source /home/anirudh/code/repos/dotfiles/vim/plugins/magit.vim
source /home/anirudh/code/repos/dotfiles/vim/plugins/mappings.vim
source /home/anirudh/code/repos/dotfiles/vim/plugins/tree.vim
source /home/anirudh/code/repos/dotfiles/vim/plugins/window-swap.vim
