Plug 'preservim/nerdcommenter'
Plug 'neoclide/coc.nvim', {'branch':'release'}
Plug 'scrooloose/nerdtree'
Plug 'airblade/vim-gitgutter'
Plug 'wesq3/vim-windowswap'
Plug 'itchyny/lightline.vim'
Plug 'joshdick/onedark.vim'
"Plug 'itchyny/lightline.vim'
Plug 'jreybert/vimagit'
Plug '~/.fzf'
Plug 'junegunn/fzf', { 'do': {-> fzf#install()}}
Plug 'junegunn/fzf.vim'
Plug 'vim-python/python-syntax'
Plug 'kmonad/kmonad-vim'
Plug 'github/copilot.vim'
Plug 'joshdick/onedark.vim'
