# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt autocd extendedglob nomatch notify
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/akilambi/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

source /home/akilambi/code/repos/dotfiles/zsh/aliases

# for git branch details at commandline
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '%b '

setopt PROMPT_SUBST
PROMPT='%F{blue}%*%f %F{cyan}%~%f %F{magenta}${vcs_info_msg_0_}%f$ '
